### ISSUE TITLE
大作业内容补充

### ISSUE THREAD

**Issue by taichiCourse01** [Jamin-Yang/taichi_homework#2]
Hi @Jamin-Yang,

非常感谢你提交的太极图形课大作业。

经过讨论我们觉得，目前你的作业想要通过太极图形课大作业的要求还需要完善更多信息，可以参考[大作业模板](https://github.com/taichiCourse01/taichi_course_final_project)。

具体的完善信息：
    1. 增加对作业原理的详细介绍（因为shadertoy上有源代码，我们需要确认你理解了代码内容）
    2. 提供更详细的代码注释和代码讲解。

如果你能够在 1月14日24:00（北京时间）之前完成以上修改，我们就会通过你的大作业。
你也将会收到我们提供的课程结业证书和礼物。

祝好！

太极图形课

**Comment by Jamin-Yang** [comment]
你好！
>我已经按照要求修改了我的代码，加上了注释
>如果代码还有需要改善的地方，麻烦再通知我
>
>辛苦老师和助教了
>
